const trans = {
    'Add_The_siapitd': 'The subscriber is already present in the database.',
    'Exp_Please_sctywte': 'Please select columns that you want to export',
    'Exp_Leave_tbfnloo': 'Leave these blank for no limit or offset',
    'Pro_Please_saof': 'Please select an option first',
    'Map_Status_ftns': 'Status for the new subscribers',
    'Map_Importing_CfyCPD': 'Importing Contacts from your CSV. Please Do not close this modal',
    'Map_Total_S_I': 'Total Skipped (Including Invalid):',
    'Map_Completed_Ycctmn': 'Completed. You can close this modal now',
    'Map_Contacts_tad': 'Contacts that are duplicate',
    'Map_Subscribers_is': 'Subscribers imported successfully.',
    'Use_Some_otumyc': 'Some of the users matching your criteria',
    'Use_Please_dnctm': 'Please do not close this modal.',
    'Das_View_ESSS': 'View Email Sending Service Settings',
    'Das_Activate_FFI': 'Activate Fluent Forms Integration',
    'Cre_Please_pNotS': 'Please provide Name of this Segment',
    '_Cu_Estimated_Cboys': 'Estimated Contacts based on your selections:',
    'Cam_Send_osce': 'Send or schedule campaign emails',
    'Cam_Continue_S': 'Continue [Subject & Settings]',
    'Cam_Please_peB': 'Please provide email Body.',
    'Cam_Email_bsu': 'Email body successfully updated',
    'Cam_Type_cetstolbtsc': 'Type custom email to send test or leave blank to send current user email',
    'Cam_Continue_TNS_': 'Continue To Next Step [Recipients]',
    'Cam_Please_peS': 'Please provide email Subject.',
    'Cam_Please_pSLfAT': 'Please provide Subject Lines for A/B Test.',
    'Cam_Please_peb': 'Please provide email body.',
    'Cam_Looks_lydnbaecy': 'Looks like you did not broadcast any email campaign yet',
    'Cam_Create_YFEC': 'Create Your First Email Campaign',
    'Rec_Continue_TNS_aS': 'Continue To Next Step [Review and Send]',
    'Rec_Please_dnctw': 'Please do not close this window.',
    'Rec_Processing_EhMit': 'Processing Error happened. Maybe it\'s timeout error. Resume or StartOver',
    'Sch_Emails_wbsast': 'Emails will be sent at scheduled time.',
    'Vie_This_cino_sNEwbs': 'This campaign is now on "Paused" state. No Emails will be sent',
    'Vie_Your_easrn': 'Your emails are sending right now....',
    'Vie_This_chbs': 'This campaign has been scheduled.',
    'Vie_The_ewbsboysdat': 'The emails will be sent based on your set date and time.',
    'Vie_Emails_asatm': 'Emails are sending at this moment',
    'Cam_Add_Remove_ToyCb': 'Add/Remove Tag of your Contacts based on email interaction',
    'Cam_Select_Utwc_MfaS': 'Select URLS that where clicked (Will Match for any Selected URLs)',
    'Cam_Sorry_nlftcc': 'Sorry no links found that contacts clicked',
    'Cam_Remove_TFS': 'Remove Tags From Subscribers',
    'Cam_Contacts_psf': 'Contacts processed so far...',
    'Cam_contacts_hbp': 'contacts has been processed',
    'Cam_Select_Swote': 'Select Subscribers who open the emails',
    'Cam_Select_Swdnoe': 'Select Subscribers who did not open email',
    'Cam_Select_Swcsl': 'Select Subscribers who click selected links',
    'Cam_Broadcast_Schedu': 'Broadcast/Schedule This Email Campaign Now',
    'Cam_If_yteiaYcbten': 'If you think everything is alright. You can broadcast/Schedule the emails now.',
    'Cam_Current_ST_oySS': 'Current Server Time (Based on your Site Settings)',
    '_Ca_failed_tstrTR': 'failed to send to recipients. Try Resending',
    '_Ca_Please_utptutf': 'Please upgrade to pro to use this feature',
    'All_Looks_lydnsasey': 'Looks like you did not set any sequence emails yet',
    'All_Create_YFES': 'Create Your First Email Sequence',
    'Edi_If_ysatrtFstettt': 'If you select a time range then FluentCRM schedule the email to that time range',
    'Vie_Get_swaaetts': 'Get started with adding an email to this sequence',
    'Vie_Add_aSE': 'Add another Sequence Email',
    'Vie_Set_CFNaE': 'Set Custom From Name and Email',
    'Vie_Please_msteisbyS': 'Please make sure this email is supported by your SMTP/SES',
    '_Su_Please_ntsewbstt': 'Please note that, sequences emails will be scheduled to the contacts as per the current state',
    '_Su_All_SLashbaSttsE': 'All Selected List and subscribers has been added Successfully to this sequence. Emails will be sent as per your configuration',
    '_Su_Subscribers_hbat': 'Subscribers has been added to this email sequence',
    '_Su_Invalid_solatisi': 'Invalid selection of lists and tags in subscribers included.',
    '_Su_Subscribers_hbas': 'Subscribers have been added successfully to this sequence.',
    'For_Fluent_FtacwyC': 'Fluent Forms that are connected with your CRM',
    'For_Grow_YAbOF': 'Grow Your Audience by Opt-in Forms',
    'For_Looks_Lydncafy': 'Looks Like you did not create any forms yet!',
    '_Cr_Your_fhbcs': 'Your form has been created successfully',
    '_Cr_Enable_DOC': 'Enable Double Opt-in Confirmation',
    '_Cr_This_fwbciFFaycc': 'This form will be created in Fluent Forms and you can customize anytime',
    '_Cr_Please_fuatf': 'Please fill up all the fields',
    '_Bl_Actions_battywtf': 'Actions blocks are tasks that you want to fire from your side for the target contact',
    '_Bl_These_aygityuwda': 'These are your goal/trigger item that your user will do and you can measure these steps or adding into this funnel',
    '_Bl_Use_tbtcspfysc': 'Use the blocks to create separate path for your segmented contacts',
    'Fun_Total_Rftf': 'Total Revenue from this funnel (goals only)',
    'Fun_Waiting_fdoc': 'Waiting for double opt-in confirmation',
    '_Cr_Create_aAF': 'Create an Automation Funnel',
    '_In_Wfdoc': ' - Waiting for double opt-in confirmation',
    '_In_Wfna': ' - Waiting for next action',
    '_In_Wfdc': ' - Waiting for double-optin confirmation',
    'Lis_List_acoycYcalaa': 'List are categories of your contacts. You can add lists and assign contacts to your list for better segmentation',
    'Pro_Activities_otcwb': 'Activities of this contact will be shown here',
    'Pro_Emails_fdcaa': 'Emails from different campaigns and automations',
    'Pro_Contact_F_A': 'Contact Files & Attachments',
    'Pro_Form_SfFFwbshCFF': 'Form Submission from Fluent Forms will be shown here. Currently, Fluent Forms is not installed',
    'Pro_Contact_N_A': 'Contact Notes & Activities',
    'Pro_No_NfPatfn': 'No Note found. Please add the first note',
    'Pro_Purchase_hfEwbsh': 'Purchase history from EDD/WooCommerce will be shown here. Currently no E-Commerce Plugin found in your installation',
    'Pro_Change_SS': 'Change Subscription Status',
    'Set_SMTP_Email_SS': 'SMTP/Email Service Settings',
    'Lin_SmartLinks_aytta': 'SmartLinks allow you to tag and segment your subscribers when they click a link in an email, on your site or anywhere!',
    'Lin_This_iapfPdtFPta': 'This is a premium feature. Please download the FluentCRM Pro to activate this feature.',
    '_Cr_Please_utfsuawau': 'Please use the following smart url and when a user click a link in an email, on your site or anywhere then your selected tags and lists will be applied.',
    'Tag_Tags_alLbmwtfyci': 'Tags are like Lists but more ways to filter your contacts inside a list',
    'For_Internal_S_': 'Internal Subtitle (Optional)',
    'Con_Are_ystdt': 'Are you sure to delete this?',
    'Raw_Please_PHoyE': 'Please Provide HTML of your Email',
    'Ema_Enable_Atfes': 'Enable A/B testing for email subjects',
    'Ema_Your_ppwbctpair': 'Your provided priority will be converted to percent and it\'s relative',
    'Ema_Add_UPFU': 'Add UTM Parameters For URLs',
    'Gut_Suggesting_vB6t8': 'Suggesting value: Between 600 to 800',
    'Rec_Select_LaTtywtse': 'Select Lists and Tags that you want to send emails for this campaign. You can create multiple row to send to all of them',
    'Rec_This_wfaac': 'This will filter all available contacts',
    'Rec_Select_Loasfatst': 'Select List or all subscribers first and then select tag',
    'Rec_Select_LaTtywtef': 'Select Lists and Tags that you want to exclude from this campaign. Excluded contacts will be subtracted from your included selection',
    'Rec_Please_stwdsywts': 'Please select to which dynamic segment you want to send emails for this campaign',
    'Rec_contacts_fboys': 'contacts found based on your selection',
    'Rec_All_coSLs': 'All contacts on Selected List segment',
    'fluentsmtp.desc': 'Looks like you did not install FluentSMTP yet. FluentSMTP is the the ultimate SMTP & Email Service Connection Plugin for WordPress.',
    'permission.title': 'Looks like you do not have permission to view the requested resource.',
    'permission.desc': 'Please contact your site administrator to request the permission',
    'testEmail.instruction': 'Type custom email to send test or leave blank to send current user email',
    'csv.download_desc': 'Please make sure your csv file has unique headers. Otherwise, it may fail to import',
    'custom_segment.name_desc': 'Please provide a name so you can identify easily',
    'business_settings.name_help': 'Your Business name will be used in Emails, Unsubscribe Pages and public front interfaces',
    'business_settings.address_help': 'Your Business Address will be used in Emails. The address is required as per anti-spam rules',
    'business_settings.logo_help': 'Your Business Logo, It will be used in Public Facing pages',
    'quick_links.ff_desc': 'Fluent Forms is a free form plugin for WordPress that is integrated with FluentCRM',
    'AllSegments.desc': 'Create dynamic Segments of contacts by using dynamic contact properties and filter your target audience',
    'Forms.desc': 'Fluent Forms that are connected with your CRM',
    'Forms.if_need_desc': 'If you need to create and connect more advanced forms please use Fluent Forms.',
    'SourceSelector.title': 'Select Source from where you want to import your contacts',
    'CreateForm.desc': 'Paste the following shortcode to any page or post to start growing your audience',
    'Mapper.title': 'Map CSV Fields with Contact Property',
    'Mapper.title_desc': 'Please map the csv headers with the respective subscriber fields.',
    'Enable Specific Days Only': 'Enable Specific Days Only',
    'Please select allowed days to send emails': 'Please select allowed days to send emails',
    'Monday': 'Monday',
    'Tuesday': 'Tuesday',
    'Wednesday': 'Wednesday',
    'Thursday': 'Thursday',
    'Friday': 'Friday',
    'Saturday': 'Saturday',
    'Sunday': 'Sunday'
};

module.exports = trans;
