<?php

namespace FluentCrm\App\Services;

class TransStrings
{
    public static function getStrings()
    {
        return [
            'Contacts'                                                                => __('Contacts', 'fluent-crm'),
            'Contact ID:'                                                             => __('Contact ID:', 'fluent-crm'),
            'Status'                                                                  => __('Status', 'fluent-crm'),
            'Email'                                                                   => __('Email', 'fluent-crm'),
            'quick_links.ff_desc'                                                     => __('Use Fluent Forms to create opt-in forms and grow your audience', 'fluent-crm'),
            'Mapper.title'                                                            => __('Map CSV Fields with Contact Property', 'fluent-crm'),
            'csv.download_desc'                                                       => __('Please make sure your CSV is utf-8 encoded. Otherwise it may not work properly. You can upload any CSV and in the next screen you can map the data', 'fluent-crm'),
            'Mapper.title_desc'                                                       => __('Please map the csv headers with the respective subscriber fields.', 'fluent-crm'),
            'SourceSelector.title'                                                    => __('Select Source from where you want to import your contacts', 'fluent-crm'),
            'custom_segment.name_desc'                                                => __('Enter a descriptive title. This is shown on internal pages only.', 'fluent-crm'),
            'AllSegments.desc'                                                        => __('You can filter your contacts based on different attributes and create a dynamic list.', 'fluent-crm'),
            'Forms.desc'                                                              => __('Use Fluent Forms to create opt-in forms and grow your audience. Please activate this feature and it will install Fluent Forms and activate this integration for you', 'fluent-crm'),
            'Forms.if_need_desc'                                                      => __('If you need to create and connect more advanced forms please use Fluent Forms.', 'fluent-crm'),
            'CreateForm.desc'                                                         => __('Paste the following shortcode to any page or post to start growing your audience', 'fluent-crm'),
            'Forms'                                                                   => __('Forms', 'fluent-crm'),
            'Create a New Form'                                                       => __('Create a New Form', 'fluent-crm'),
            'Looks Like you did not create any forms yet!'                            => __('Looks Like you did not create any forms yet!', 'fluent-crm'),
            'Create Your First Form'                                                  => __('Create Your First Form', 'fluent-crm'),
            'Fluent Forms that are connected with your CRM'                           => __('Fluent Forms that are connected with your CRM', 'fluent-crm'),
            'ID'                                                                      => __('ID', 'fluent-crm'),
            'Title'                                                                   => __('Title', 'fluent-crm'),
            'Info'                                                                    => __('Info', 'fluent-crm'),
            'Shortcode'                                                               => __('Shortcode', 'fluent-crm'),
            'Created at'                                                              => __('Created at', 'fluent-crm'),
            'Actions'                                                                 => __('Actions', 'fluent-crm'),
            'Preview Form'                                                            => __('Preview Form', 'fluent-crm'),
            'Edit Integration Settings'                                               => __('Edit Integration Settings', 'fluent-crm'),
            'Edit Form'                                                               => __('Edit Form', 'fluent-crm'),
            'Select a template'                                                       => __('Select a template', 'fluent-crm'),
            'Enable Double Opt-in Confirmation'                                       => __('Enable Double Opt-in Confirmation', 'fluent-crm'),
            'This form will be created in Fluent Forms and you can customize anytime' => __('This form will be created in Fluent Forms and you can customize anytime', 'fluent-crm'),
            'Create Form'                                                             => __('Create Form', 'fluent-crm'),
            'Subscribers Growth'                                                      => __('Subscribers Growth', 'fluent-crm'),
            'Email Sending Stats'                                                     => __('Email Sending Stats', 'fluent-crm'),
            'Email Open Stats'                                                        => __('Email Open Stats', 'fluent-crm'),
            'Email Link Click Stats'                                                  => __('Email Link Click Stats', 'fluent-crm'),
            'Quick Overview'                                                          => __('Quick Overview', 'fluent-crm'),
            'Quick Links'                                                             => __('Quick Links', 'fluent-crm'),
            'Dashboard'                                                               => __('Dashboard', 'fluent-crm'),
            'By Date'                                                                 => __('By Date', 'fluent-crm'),
            'Cumulative'                                                              => __('Cumulative', 'fluent-crm'),
            'Name'                                                                    => __('Name', 'fluent-crm'),
            'Add'                                                                     => __('Add', 'fluent-crm'),
            'Import'                                                                  => __('Import', 'fluent-crm'),
            'Add New Contact'                                                         => __('Add New Contact', 'fluent-crm'),
            'Cancel'                                                                  => __('Cancel', 'fluent-crm'),
            'Confirm'                                                                 => __('Confirm', 'fluent-crm'),
            'Filtered by'                                                             => __('Filtered by', 'fluent-crm'),
            'Search...'                                                               => __('Search...', 'fluent-crm'),
            'Choose an option:'                                                       => __('Choose an option:', 'fluent-crm'),
            'Contact Type'                                                            => __('Contact Type', 'fluent-crm'),
            'Tags'                                                                    => __('Tags', 'fluent-crm'),
            'Lists'                                                                   => __('Lists', 'fluent-crm'),
            'Source'                                                                  => __('Source', 'fluent-crm'),
            'Phone'                                                                   => __('Phone', 'fluent-crm'),
            'Country'                                                                 => __('Country', 'fluent-crm'),
            'Created At'                                                              => __('Created At', 'fluent-crm'),
            'Last Change Date'                                                        => __('Last Change Date', 'fluent-crm'),
            'Last Activity'                                                           => __('Last Activity', 'fluent-crm'),
            'Search Type and Enter...'                                                => __('Search Type and Enter...', 'fluent-crm'),
            'Date Added'                                                              => __('Date Added', 'fluent-crm'),
            'Basic Info'                                                              => __('Basic Info', 'fluent-crm'),
            'Prefix'                                                                  => __('Prefix', 'fluent-crm'),
            'First Name'                                                              => __('First Name', 'fluent-crm'),
            'Last Name'                                                               => __('Last Name', 'fluent-crm'),
            'Date of Birth'                                                           => __('Date of Birth', 'fluent-crm'),
            'Pick a date'                                                             => __('Pick a date', 'fluent-crm'),
            'Add Address Info'                                                        => __('Add Address Info', 'fluent-crm'),
            'Add Custom Data'                                                         => __('Add Custom Data', 'fluent-crm'),
            'Identifiers'                                                             => __('Identifiers', 'fluent-crm'),
            'Select lists'                                                            => __('Select lists', 'fluent-crm'),
            'Select tags'                                                             => __('Select tags', 'fluent-crm'),
            'Contact Source'                                                          => __('Contact Source', 'fluent-crm'),
            'Configuration'                                                           => __('Configuration', 'fluent-crm'),
            'CSV File'                                                                => __('CSV File', 'fluent-crm'),
            'WordPress Users'                                                         => __('WordPress Users', 'fluent-crm'),
            'Next'                                                                    => __('Next', 'fluent-crm'),
            'Select Your CSV Delimiter'                                               => __('Select Your CSV Delimiter', 'fluent-crm'),
            'Next [Map Columns]'                                                      => __('Next [Map Columns]', 'fluent-crm'),
            'Dynamic Segments'                                                        => __('Dynamic Segments', 'fluent-crm'),
            'Create Custom Segment'                                                   => __('Create Custom Segment', 'fluent-crm'),
            'System Defined'                                                          => __('System Defined', 'fluent-crm'),
        ];
    }
}