<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'FluentEmogrifier\Vendor\\Symfony\\Component\\CssSelector\\' => array($vendorDir . '/symfony/css-selector'),
    'FluentEmogrifier\Vendor\\Sabberworm\\CSS\\' => array($vendorDir . '/sabberworm/php-css-parser/src'),
    'FluentEmogrifier\Vendor\\Pelago\\Emogrifier\\' => array($vendorDir . '/pelago/emogrifier/src'),
);
