<?php

 // Auto generated by wpfluent Installer.

 return array (
  'name' => __('Fluent Crm', 'fluent-crm'),
  'slug' => 'fluent-crm',
  'domain_path' => '/language',
  'text_domain' => 'fluent-crm',
  'hook_prefix' => 'fluentcrm_',
  'rest_namespace' => 'fluent-crm',
  'rest_version' => 'v2',
  'env' => 'dev',
);
